Added Description about the project
osl-incubator/cookiecutter-python pull request #76
Opened 2023-04-04 04:05 UTC by Satarupa22-SD

## Pull Request description

I have noticed that a project description was missing in the readme file. This would enable the project to be more accessible and increase its usability.

 improving documentation 

## How to test these changes

* ```...```

## Pull Request checklists

This PR is a:
- [ ] bug-fix
- [ ] new feature
- [ ] maintenance

About this PR:
- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [ ] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:
- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more complexity.
- [ ] New and old tests passed locally.

## Additional information

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved .
```

2023-04-04 11:59 UTC, xmnlab requested changes
thanks for working on that @Satarupa22-SD !
In general looks good. could you add that information about that we aim to support the recommendations from pyopensci pls?

2023-04-04 15:40 UTC, xmnlab commented
@Satarupa22-SD you maybe can use this as reference (feel free to change it):

> This cookiecutter Python template  aims to provide the workflow, libraries, and tools recommended by PyOpenSci. In addition, this template includes extra options that can improve the development workflow.
> PyOpenSci is currently conducting an investigation to identify tools, libraries, best practices, and workflows used by the most notable scientific Python communities.

2023-04-05 04:16 UTC, Satarupa22-SD commented
@xmnlab added the details

2023-04-05 05:01 UTC, xmnlab commented on README.md
> +PyOpenSci is actively conducting research to determine the tools, libraries, best practices, and workflows utilized by significant scientific Python groups. As a result, this template offers customer
```suggestion
Open Science Labs Scientific Python cookiecutter  template is based mainly on the PyOpenSci recommendations who is actively conducting research to determine the tools, libraries, best practices, and workflows utilized by significant scientific Python groups. As a result, this template offers to authors a place to start that adheres with industry standards and may be adjusted to meet particular project requirements.
```

2023-04-05 05:03 UTC, xmnlab requested changes
@Satarupa22-SD thanks for working on that!
I just added a suggestion here and please try to have lines with max 79 characters
thank you!

2023-04-05 11:44 UTC, xmnlab approved these changes
Looks good to me! Thanks for working on that!

2023-04-05 11:44 UTC, merged