feat(template): Adding pydocstyle to the template
osl-incubator/cookiecutter-python pull request #89
Opened 2023-05-22 20:55 UTC by YurelyCamacho

## Pull Request description
Adding pydocstyle as an option to the template and setting pre-commit hook

Solving issue #37

## Pull Request checklists

This PR is a:
- [ ] bug-fix
- [x ] new feature
- [ ] maintenance

About this PR:
- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [x ] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:
- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more complexity.
- [x ] New and old tests passed locally.

## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [x ] I managed to test the new changes locally
- [ x] I confirm that the issues mentioned were fixed/resolved .
```

2023-05-22 21:09 UTC, YurelyCamacho commented
@xmnlab I noticed that in Anavelyz's PR on bandit, you asked him to add some documentation. I'm going to do the same here.

2023-05-22 21:32 UTC, xmnlab requested changes
As you mentioned we need the docs in the project and the template side.
Other than that, just added a small comment here about the pkg  version

2023-05-22 21:32 UTC, xmnlab commented on {{cookiecutter.project_slug}}/pyproject.toml
> +pydocstyle = "6.3.0"
```suggestion
pydocstyle = "^6.3.0"
```

2023-05-22 22:32 UTC, merged

2023-05-22 22:34 UTC, YurelyCamacho commented
@xmnlab Sorry, I don't know what I did here. Could you help me, please

2023-05-22 22:48 UTC, xmnlab commented
No worries, just open a new PR with the missing pieces

2023-05-22 23:27 UTC, YurelyCamacho commented
@xmnlab Everything is already in this PR, if you can check it, please. The last thing I added was the documentation and the change in version.

2023-05-22 23:59 UTC, xmnlab commented
@YurelyCamacho this PR is already merged
the commit you pushed after you merged the PR will not be included to the main anymore.
please open a new PR with the latest changes. thanks!

2023-05-23 00:00 UTC, xmnlab commented
although, it seems your last commit is just a revert, is that correct?
sorry, I am a bit confused.

2023-05-23 00:01 UTC, xmnlab commented on {{cookiecutter.project_slug}}/docs/index.md
> +- This package uses [pydocstyle](http://www.pydocstyle.org/en/stable/)
you will need to check first if the user selected pydocstyle.
do it in a new PR.

2023-05-23 00:02 UTC, xmnlab commented on {{cookiecutter.project_slug}}/README.md
> +- This package uses [pydocstyle](http://www.pydocstyle.org/en/stable/)
you will need to check first if the user selected pydocstyle.
do it in a new PR.